# Generated by Django 4.2.2 on 2023-08-06 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=500)),
                ('employment_type', models.CharField(max_length=9)),
                ('employment_start', models.CharField(max_length=7)),
                ('employment_end', models.CharField(max_length=7)),
                ('currently_employed', models.BooleanField()),
                ('flexibility_rating', models.IntegerField()),
                ('benefits_rating', models.IntegerField()),
                ('compensation_rating', models.IntegerField()),
                ('overall_rating', models.IntegerField()),
                ('review_text', models.TextField()),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now)),
                ('user_ip', models.GenericIPAddressField(protocol='IPv4')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('maps_id', models.CharField(max_length=500)),
                ('formatted_address', models.CharField(max_length=1000)),
                ('review_count', models.IntegerField(default=0)),
                ('review_averages', models.JSONField(default={'benefits': 'N/A', 'compensation': 'N/A', 'flexibility': 'N/A', 'overall': 'N/A'})),
                ('reviews', models.ManyToManyField(to='page.review')),
            ],
        ),
    ]
